apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: secrets
          secret:
            secretName: {{ template "secret_name" . }}
        - name: mglogs-persistent-storage
          persistentVolumeClaim:
            claimName: mglogs
        - name: sqlite-databases
          emptyDir: {}
        - name: fast-logs
          emptyDir: {}
      containers:
        - name: fpm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "fpm_image" . }}"
          imagePullPolicy: {{ .Values.image.fpm.pullPolicy }}
          env:
          - name: APP_ENV
            value: {{ .Values.environment }}
          - name: APP_URL
            value: {{ .Values.app_url }}
          - name: REDIS_HOST
            value: {{ .Release.Name}}-redis-master.metager-2.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REVERB_HOST
            value: {{ .Values.ingress.hosts[0].host}}
          {{- range $name, $value := .Values.env }}
          - name: {{ $name }}
            value: {{ $value }}
          {{- end }}
          volumeMounts:
          - name: secrets
            mountPath: /metager/metager_app/.env
            subPath: ENV_PRODUCTION
            readOnly: true
          - name: secrets
            mountPath: /metager/metager_app/config/sumas.json
            subPath: SUMAS_JSON
          - name: secrets
            mountPath: /metager/metager_app/config/suggestions.json
            subPath: SUGGESTIONS
          - name: secrets
            mountPath: /metager/metager_app/config/blacklistDomains.txt
            subPath: BLACKLIST_DOMAINS
          - name: secrets
            mountPath: /metager/metager_app/config/blacklistUrl.txt
            subPath: BLACKLIST_URL
          - name: secrets
            mountPath: /metager/metager_app/config/adBlacklistDomains.txt
            subPath: ADBLACKLIST_DOMAINS
          - name: secrets
            mountPath: /metager/metager_app/config/adBlacklistUrl.txt
            subPath: ADBLACKLIST_URL
          - name: secrets
            mountPath: /metager/metager_app/config/blacklistDescriptionUrl.txt
            subPath: BLACKLIST_DESCRIPTION_URL
          - name: mglogs-persistent-storage
            mountPath: /metager/metager_app/storage/metager
            readOnly: false
          - name: sqlite-databases
            mountPath: /metager/metager_app/database/databases
          - name: fast-logs
            mountPath: /metager/metager_app/storage/metager/fast_dir
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /health-check/liveness
              port: http
          startupProbe:
            tcpSocket:
              port: 9000
            failureThreshold: 60
            periodSeconds: 1
          resources:
            requests:
              {{- toYaml .Values.resources.requests.fpm | nindent 14 }}
            limits: {}
        - name: scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "fpm_image" . }}"
          command: ["/usr/local/bin/php"]
          args: ["artisan", "schedule:work-mg"]
          imagePullPolicy: {{ .Values.image.fpm.pullPolicy }}
          env:
          - name: APP_ENV
            value: {{ .Values.environment }}
          - name: APP_URL
            value: {{ .Values.app_url }}
          - name: REDIS_HOST
            value: {{ .Release.Name}}-redis-master.metager-2.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REVERB_HOST
            value: {{ .Values.ingress.hosts[0].host}}
          {{- range $name, $value := .Values.env }}
          - name: {{ $name }}
            value: {{ $value }}
          {{- end }}
          volumeMounts:
          - name: secrets
            mountPath: /metager/metager_app/.env
            subPath: ENV_PRODUCTION
            readOnly: true
          - name: mglogs-persistent-storage
            mountPath: /metager/metager_app/storage/metager
            readOnly: false
          - name: sqlite-databases
            mountPath: /metager/metager_app/database/databases
          - name: fast-logs
            mountPath: /metager/metager_app/storage/metager/fast_dir
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check/liveness-scheduler
              port: http
          readinessProbe:
            httpGet:
              path: /health-check/liveness-scheduler
              port: http
          startupProbe:
            httpGet:
              path: /health-check/liveness-scheduler
              port: http
          resources:
            requests:
              {{- toYaml .Values.resources.requests.scheduler | nindent 14 }}
            limits: {}
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "fpm_image" . }}"
          command: ["/usr/local/bin/php"]
          args: ["artisan", "requests:fetcher"]
          imagePullPolicy: {{ .Values.image.fpm.pullPolicy }}
          env:
          - name: APP_ENV
            value: {{ .Values.environment }}
          - name: REDIS_HOST
            value: {{ .Release.Name}}-redis-master.metager-2.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REVERB_HOST
            value: {{ .Values.ingress.hosts[0].host}}
          {{- range $name, $value := .Values.env }}
          - name: {{ $name }}
            value: {{ $value }}
          {{- end }}
          volumeMounts:
          - name: secrets
            mountPath: /metager/metager_app/.env
            subPath: ENV_PRODUCTION
            readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check/liveness-worker
              port: http
          readinessProbe:
            httpGet:
              path: /health-check/liveness-worker
              port: http
          startupProbe:
            httpGet:
              path: /health-check/liveness-worker
              port: http
          resources:
            requests:
              {{- toYaml .Values.resources.requests.worker | nindent 14 }}
            limits:
        - name: reverb
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "fpm_image" . }}"
          command: ["/usr/local/bin/php"]
          args: ["artisan", "reverb:start", "--port=8081"]
          imagePullPolicy: {{ .Values.image.fpm.pullPolicy }}
          env:
          - name: APP_ENV
            value: {{ .Values.environment }}
          - name: REDIS_HOST
            value: {{ .Release.Name}}-redis-master.metager-2.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REVERB_HOST
            value: {{ .Values.ingress.hosts[0].host}}
          {{- range $name, $value := .Values.env }}
          - name: {{ $name }}
            value: {{ $value }}
          {{- end }}
          volumeMounts:
          - name: secrets
            mountPath: /metager/metager_app/.env
            subPath: ENV_PRODUCTION
            readOnly: true
          ports:
            - name: reverb
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - pgrep
              - -f
              - reverb:start
          readinessProbe:
            exec:
              command:
              - pgrep
              - -f
              - reverb:start
          startupProbe:
            exec:
              command:
              - pgrep
              - -f
              - reverb:start
          resources:
            requests:
              {{- toYaml .Values.resources.requests.worker | nindent 14 }}
            limits:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ template "nginx_image" . }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check/nginx
              port: http
          readinessProbe:
            httpGet:
              path: /health-check/nginx
              port: http
          startupProbe:
            httpGet:
              path: /health-check/nginx
              port: http
            failureThreshold: 60
            periodSeconds: 1
          resources:
            requests:
              {{- toYaml .Values.resources.requests.nginx | nindent 14 }}
            limits: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: {{ .Release.Name }}
                topologyKey: kubernetes.io/hostname
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
