--- 
hpa: 
  enabled: false
ingress: 
  annotations: 
    kubernetes.io/tls-acme: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  tls: 
    enabled: false
service: 
  commonName: ""
  externalPort: 80
  internalPort: 80
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "80"  
